### ISSUE TITLE
The GlbExporter is missing.

### ISSUE THREAD

**Issue by bitdream** [mgsx-dev/gdx-gltf#103]
The files from gltf exporter are not supported by Godot engine and lots of other engines...
Every time I have to convert them into glb by some external tools.
If this glb exporter is missing, what's the difference between this one and the old fbx-conv work flow?

**Comment by mgsx-dev** [comment]
> The files from gltf exporter are not supported by Godot engine and lots of other engines...
What's the issue? I tested import in Blender and it works fine.

**Comment by bitdream** [comment]
> > The files from gltf exporter are not supported by Godot engine and lots of other engines...
> 
> What's the issue? I tested import in Blender and it works fine.

It only can imported correctly in Blender. That's the issue.
It can not be imported in Godot game engine or other online glTF viewers or Windows 3D model viewer.
one example here:
https://gltf-viewer.donmccurdy.com/
error messages:
<html>
<body>
<h1 style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Validation report</h1><ul style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li><b>Format:</b><span> </span>glTF 2.0</li><li><b>Generator:</b><span> </span>GDX glTF exporter 1.0</li><li><b>Stats:</b><ul><li>448 draw calls</li><li>0 animations</li><li>448 materials</li><li>4816896 vertices</li><li>5376 triangles</li></ul></li><li><b>Extensions:</b><ul><li>None</li></ul></li></ul><hr style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Report generated by<a href="https://github.com/KhronosGroup/glTF-Validator/">KhronosGroup/glTF-Validator</a><span> </span>2.0.0-dev.3.9.</p>

Error | Message | Pointer
-- | -- | --
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/0/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/0/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/1/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/1/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/2/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/2/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/3/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/3/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/4/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/4/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/5/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/5/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/6/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/6/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/7/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/7/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/8/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/8/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/9/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/9/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/10/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/10/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/11/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/11/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/12/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/12/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/13/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/13/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/14/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/14/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/15/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/15/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/16/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/16/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/17/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/17/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/18/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/18/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/19/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT | Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}'). | /meshes/0/primitives/19/indices


</body>
</html>Validation report
Format: glTF 2.0
Generator: GDX glTF exporter 1.0
Stats:
448 draw calls
0 animations
448 materials
4816896 vertices
5376 triangles
Extensions:
None
Report generated by[KhronosGroup/glTF-Validator](https://github.com/KhronosGroup/glTF-Validator/) 2.0.0-dev.3.9.

Error	Message	Pointer
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/0/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/0/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/1/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/1/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/2/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/2/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/3/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/3/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/4/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/4/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/5/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/5/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/6/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/6/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/7/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/7/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/8/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/8/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/9/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/9/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/10/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/10/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/11/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/11/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/12/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/12/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/13/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/13/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/14/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/14/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/15/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/15/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/16/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/16/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/17/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/17/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/18/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/18/indices
MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS	accessor.min and accessor.max must be defined for POSITION attribute accessor.	/meshes/0/primitives/19/attributes/POSITION
MESH_PRIMITIVE_INDICES_ACCESSOR_INVALID_FORMAT	Invalid indices accessor format '{SCALAR, SHORT}'. Must be one of ('{SCALAR, UNSIGNED_BYTE}', '{SCALAR, UNSIGNED_SHORT}', '{SCALAR, UNSIGNED_INT}').	/meshes/0/primitives/19/indices

**Comment by mgsx-dev** [comment]
it should be OK now

**Comment by bitdream** [comment]
Thanks. The issue is indeed fixed. 
But please come back to the other question: do you have plan to add the GlbExporter in near future?
