### ISSUE TITLE
Cannot use pattern matching in instanceof due to "sourceCompatibility = 1.8" in gradle build

### ISSUE THREAD

**Issue by dar-dev** [mgsx-dev/gdx-gltf#108]
We need to move to a more modern compiler in order to use better, readable and faster java code

**Comment by mgsx-dev** [comment]
only ibl-composer module is 1.8 compatible. All other modules are 1.7 compatible due to iOS mainly, see https://github.com/libgdx/libgdx/issues/5487 once libgdx support 1.7, i'll surely upgrade gdx-gltf (as most libs)
