### ISSUE TITLE
IBL: ability to create different sized maps for Skybox and radiance

### ISSUE THREAD

**Issue by dar-dev** [mgsx-dev/gdx-gltf#110]
For quality reason and GPU usage sometimes it would be better to create high resolution skybox and low res radiance maps.

--

**Comment by mgsx-dev** [comment]
That's already the case :-) see https://github.com/mgsx-dev/gdx-gltf/blob/08779fcd547efe0155b4bfae07432c9c96f7c987/ibl-composer/src/net/mgsx/gltf/ibl/model/IBLSettings.java#L7
