### ISSUE TITLE
Model transparent sorting

### ISSUE THREAD

**Issue by MikOfClassX** [mgsx-dev/gdx-gltf#121]
Hello,

I think there may be an issue in renderables transparent sorting you may look into.

https://github.com/mgsx-dev/gdx-gltf/assets/6151192/65c202de-84f2-48ca-a513-26af6be15156

**Here's the test model file**

[atest.zip](https://github.com/mgsx-dev/gdx-gltf/files/14067722/atest.zip)

**Comment by mgsx-dev** [comment]
Rendrer colliding transparent object is a classic issue (OpenGL limitation), not related to libgdx.

in your example, both objects have blended material, if you remove blending attribute from blue cube material, it displays properly.
