### ISSUE TITLE
Fix Cascaded Shadow Maps on WebGL

### ISSUE THREAD

**Issue by MonstrousSoftware** [mgsx-dev/gdx-gltf#126]
The CascadedShadowMaps (CSM) don't work on the gdx-teavm platform, the application hangs due to errors ```GL_INVALID_OPERATION: Uniform type does not match uniform method.```

One of the reasons is that WebGL does not allow setting uniforms which were not explicitly fetched, so it is not valid to use integer arithmetic to iterate through an array, e.g. . 
```program.setUniformi(u_csmSamplers + i, unit);```

Another reason is that even with the above caveat, setting elements of a uniform array of sampler2d, does not appear to work (apart from element 0). Using individual sampler2d uniforms does work (and there is already a limitation in place that no more than 8 cascades are supported). 

The issue could be solved through minor changes in PBRShader.java and shadows.glsl.

See recent discussion on libgdx discord in the gdx-TeaVM thread and a demo of the fix at https://github.com/MonstrousSoftware/CascadedShadows

Presumably this will also fix the issue for the html/GWT platform but this has not been tested.

**Comment by MonstrousSoftware** [comment]
It also fixes the issue for html/GWT.

**Comment by mgsx-dev** [comment]
fixed by https://github.com/mgsx-dev/gdx-gltf/issues/127
