### ISSUE TITLE
update blender export documentation for Blender 2.93 LTS

### ISSUE THREAD

**Issue by mgsx-dev** [mgsx-dev/gdx-gltf#13]
GLTF exporter plugin interface changed a lot, documentation should be updated.

**Comment by sesteel** [comment]
It would be nice to document how to export different types of objects.  For example, I get strange behavior when rendering certain files.  I was trying to see what this software supports and I noticed some blender scenes I downloaded don't look quite right.  I exported a blender glass bottle to gltf but it is invisible; I haven't really investigated, but I am curious how to make something like that work.

**Comment by mgsx-dev** [comment]
@sesteel not all Blender features can be exported via GLTF, especially some advanced materials options, you should read the Blender exporter documentation first : https://docs.blender.org/manual/en/2.93/addons/import_export/scene_gltf2.html

gdx-gltf documentation goal is to state what's not supported and give some advice about export options.

**Comment by sesteel** [comment]
Make sense, thanks for the feedback.  This project works well so thank you for developing it.
