### ISSUE TITLE
Unsigned short indices are supported but still experimental

### ISSUE THREAD

**Issue by waverider404** [mgsx-dev/gdx-gltf#15]
Discovered I can't load certain gltf models

model: https://cdn.glitch.com/832401c3-8cbf-42db-acce-98209736affc%2Fscene%20(1).glb?v=1584936939510

**Comment by mgsx-dev** [comment]
> Unsigned short indices are supported but still experimental

This message is just a warning.

I'm able to load your file with the demo/viewer : 
![Screenshot 2020-03-25 00:19:13](https://user-images.githubusercontent.com/8074238/77485847-80ff7e00-6e2e-11ea-8b7b-02894338dfa5.png)

@waverider404 Could you please give more information: What's your issue precisely? any stacktrace or relevent error message? which platform? which gdx-gltf version?

**Comment by waverider404** [comment]
Sorry I just received the message, I am using the gltf-master-SNAPSHOT

**Comment by waverider404** [comment]
Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException
	at com.badlogic.gdx.utils.FloatArray.addAll(FloatArray.java:126)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.addVertex(MeshBuilder.java:503)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.addMesh(MeshBuilder.java:775)
	at com.badlogic.gdx.graphics.g3d.utils.MeshBuilder.addMesh(MeshBuilder.java:755)
	at com.badlogic.gdx.graphics.g3d.ModelCache.end(ModelCache.java:299)
	at com.mygdx.game.MyGdxGame.create(MyGdxGame.java:113)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:151)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by waverider404** [comment]
Here is my code 
`import net.mgsx.gltf.loaders.GLTFLoader;
import net.mgsx.gltf.loaders.GLBLoader;
import net.mgsx.gltf.scene3d.attributes.PBRCubemapAttribute;
import net.mgsx.gltf.scene3d.attributes.PBRTextureAttribute;
import net.mgsx.gltf.scene3d.scene.Scene;
import net.mgsx.gltf.scene3d.scene.SceneAsset;
import net.mgsx.gltf.scene3d.scene.SceneManager;
import net.mgsx.gltf.scene3d.scene.SceneSkybox;




public class MyGdxGame extends ApplicationAdapter {
	public Environment environment;
	public PerspectiveCamera cam;
	public CameraInputController camController;
	public ModelBatch modelBatch;
	public Model model;
	public ModelInstance instance;
	public Array<ModelInstance> trees = new Array<ModelInstance>();
	public ModelCache treeCache; //needed to reduce draw calls!

	HeightField field;
	Renderable ground;
	boolean morph = true;
	Texture texture;
	
	@Override
	public void create() {

		Bullet.init();
		btCollisionObject groundObject = new btCollisionObject();

		CharSequence str = groundObject.toString();
		System.out.println(str);

		environment = new Environment();
		environment.set(new ColorAttribute(ColorAttribute.AmbientLight, 0.4f, 0.4f, 0.4f, 1f));
		environment.add(new DirectionalLight().set(0.8f, 0.8f, 0.8f, -1f, -0.8f, -0.2f));

		modelBatch = new ModelBatch();

		cam = new PerspectiveCamera(67, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
		cam.position.set(10f, 10f, 10f);
		cam.lookAt(0,0,0);
		cam.near = 1f;
		cam.far = 300f;
		cam.update();

		SceneAsset model_asset = new GLBLoader().load(Gdx.files.internal("grass.glb"));
     	double range = 80;
		int count = 300*10;

		for (int index = 0; index < count; index++) {
			double x = (range / 2) - (Math.random() * range);
			double z = (range / 2) - (Math.random() * range);
			this.instance = new ModelInstance(model_asset.scene);
			this.instance.transform.setTranslation((float) x, 1.0f, (float) z);
			this.instance.transform.scale(8.5f, 8.5f, 8.5f);
			this.trees.add(this.instance);
		}
		

		Texture texture = new Texture(Gdx.files.internal("badlogic.jpg"));
	
	
		SceneAsset room_asset = new GLBLoader().load(Gdx.files.internal("room.glb"));

		
		 ModelBuilder modelBuilder = new ModelBuilder();
	        model = modelBuilder.createBox(5f, 5f, 5f, 
	            new Material(TextureAttribute.createDiffuse(texture)),
	            Usage.Position | Usage.Normal | Usage.TextureCoordinates);
	        ModelInstance boxInstance = new ModelInstance(room_asset.scene);
	        
	        this.trees.add(boxInstance);
		
		treeCache = new ModelCache();
		treeCache.begin();
		treeCache.add(trees);
		treeCache.end();

		camController = new CameraInputController(cam);
		Gdx.input.setInputProcessor(camController);
	}
`

**Comment by mgsx-dev** [comment]
indeed, model cache is not compatible with more than 32k vertices for now. I'm working on a libgdx PR  : https://github.com/libgdx/libgdx/pull/5925 which will fix it once merged.

For now, you should either keep max 32k vertices or don't use model cache.

**Comment by waverider404** [comment]
that will awesome!!

**Comment by waverider404** [comment]
The skinned model looks distorted when I animate them :(
model file : https://cdn.glitch.com/ca440387-5ef4-4401-a707-6a988d4e8bc5%2Fcynthia.glb?v=1585537867699

<img width="848" alt="Screen Shot 2020-03-29 at 11 08 16 PM" src="https://user-images.githubusercontent.com/34609417/77871539-7409d280-7212-11ea-9d5e-e32d7fd11017.png">

**Comment by mgsx-dev** [comment]
@waverider404 maybe you didn't configure num bones properly, see #6 
BTW, it would be nice to create another issue next time. Since it may be not related to unsigned short indices.

**Comment by mgsx-dev** [comment]
libgdx/libgdx#5925 has been merged, it's now possible to use ModelCache with libgdx 1.9.11-SNAPSHOT.
