### ISSUE TITLE
Quick question: Export

### ISSUE THREAD

**Issue by anonimo82** [mgsx-dev/gdx-gltf#16]
Hello everyone.
I've heard on Discord there is a export feature in the works, just wish to be sure about what is this about.
So, can I use this library to export gltf files made from inside LibGDX?

Thanks in advance for any help.

Bye, Ivano.

**Comment by mgsx-dev** [comment]
Exactly, i have a working export code right now but it needs a bit more polish. I think i'll integrate it in a working branch in this repository soon in order to let people play with it.

**Comment by anonimo82** [comment]
Thanks

**Comment by mgsx-dev** [comment]
export feature is now available in master branch
