### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by dzikoysk** [mgsx-dev/gdx-gltf#21]
Hey, first of all - this project looks amazing ❤️ I'm pretty sure that most of ppl using G3D format might be interested in this solution, they just probably don't know it even exists 😢 

More to the point, how stable and active is it? There is a couple of issues and the last commit was 3 months ago, I'm just curious about the future.

**Comment by mgsx-dev** [comment]
Hey, thank you, it's referenced here and there : 
- https://github.com/rafaskb/awesome-libgdx#visual-effects
- http://github.khronos.org/glTF-Project-Explorer/
if you think there are other places it should be referenced, please let me know :-)

It is active and pretty stable, there are no real issues right now, only questions, enhancement. 

3 months without a commit is not a big deal, especially during summer, last discussion was 6 days ago. There will be new stuff soon, don't worry i'm still there  :-)

**Comment by dzikoysk** [comment]
Thanks, I'd prefer to ask before I'll use it :)

If I were you, I would try to suggest authors of these articles to add a reference:
* https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX
* https://gamefromscratch.com/libgdx-tutorial-series 
* https://xoppa.github.io/blog/loading-models-using-libgdx

Your project is a lot easier and user-friendly for beginners and it also provides much more functionalities than the standard G3D solution. Even single reference in one of these places might be a good start. I've found this project

**Comment by mgsx-dev** [comment]
Thank you for the hint!

Actually GameFromScratch tutorials are pretty outdated and Xoppa is no longer in the house. But libgdx wiki is definitely something i can do. I want to update my docs towards Blender 2.8.3 (LTS) before, something i wanted to do soon anyway, i put that on my todo list.

Happy coding!

**Comment by dzikoysk** [comment]
They are outdated, but they're still high in search results and I'm pretty sure that a lot of people still use them 😛 

Thanks and all I can do is wish you luck :)
