### ISSUE TITLE
Control emissivie factor

### ISSUE THREAD

**Issue by dzikoysk** [mgsx-dev/gdx-gltf#22]
Hey, as a test I'm trying to port this scene: [crypt location](https://sketchfab.com/3d-models/crypt-location-ea79b3b36fc04ded845ddfe1de08957a), preview:

![image](https://user-images.githubusercontent.com/4235722/92974133-d6cfed00-f485-11ea-97e8-cf5c8134fd14.png)

As you can see it contains such a high glowing elements, but it's not really noticeable using standard values:

![image](https://user-images.githubusercontent.com/4235722/92974188-f8c96f80-f485-11ea-9f41-582aac58066f.png)

I've found that [glTF supports emissions](https://learn.foundry.com/modo/content/help/pages/shading_lighting/shader_items/gltf.html) and you've even have it in the pbr fragment shader:

https://github.com/mgsx-dev/gdx-gltf/blob/df2904c8445f1efda0588f73dd5570639ad2f4b3/gltf/src/net/mgsx/gltf/shaders/gdx-pbr.fs.glsl#L618

The model has properly marked elements with emission, I can see it in emission preview:

![image](https://user-images.githubusercontent.com/4235722/92974759-34b10480-f487-11ea-9d04-2704de3ef5be.png)

So my question is - is there any way to increase the glowing effect? I think that some kind of extra multiplication factor for emission could solve this issue.

**Comment by mgsx-dev** [comment]
@dzikoysk the glow effect you have in your picture is called "Bloom", you can achieve it via post processing effects. You can use third-party library like [gdx-vfx](https://github.com/crashinvaders/gdx-vfx) by applying a blur effect on emissive layer (as FBO) or an overall bloom effect to the scene.
