### ISSUE TITLE
Desktop demo crash when enabling outline

### ISSUE THREAD

**Issue by Hangman** [mgsx-dev/gdx-gltf#26]
The stack trace should speak for itself.
But for the sake of completeness, the steps to reproduce:
- run the demo jar
- [optional] load a model
- enable the outline
=> crash

Demo version: 1.0.0

![image](https://user-images.githubusercontent.com/108926/93539930-6d068600-f952-11ea-9fe6-9e2ec25ec3f1.png)

**Comment by mgsx-dev** [comment]
it's fixed, i replaced demo jar in release section (patch1)
