### ISSUE TITLE
IBL Composer crash when setting unsupported environment map size

### ISSUE THREAD

**Issue by Hangman** [mgsx-dev/gdx-gltf#27]
Steps to reproduce:
- run IBL composer
- open this HDRI file [https://hdrihaven.com/hdri/?c=night&h=blaubeuren_night](url) 4k version
- set the environment map size to 8k
=> crash

It could show a message that the size is unsupported or even better disable the options to choose those resolutions.

This also happens when setting the irradience map to 8k but not when setting the radience map to 8k.
I got no stack trace for it though.

![image](https://user-images.githubusercontent.com/108926/93540732-e1dabf80-f954-11ea-8eeb-6e435834e6f3.png)

And just to make it a little more challenging for you:
The crash won't occur with this hdri map [https://hdrihaven.com/hdri/?c=nature&h=gamrig](url) in 8k and setting the environment map size to 16k. At least it doesn't crash for me.

**Comment by mgsx-dev** [comment]
There was already some checks to get max resolution supported by GPU but it's caused by out of memory errors. Since it depends on GPU loads at the time you generate the maps, i preferred catching errors and display a message to the user, the app doesn't crash in this case.

**Comment by mgsx-dev** [comment]
updated version available in 1.0.0 release section as "2.0.0-preview"
