### ISSUE TITLE
Exported GTLF file from Blender doesn't show up

### ISSUE THREAD

**Issue by edgarssilva** [mgsx-dev/gdx-gltf#35]
Hi there, I find this library very insteresting so I decided to give it a shot.

But when I load a gltf file from Blender it doesn't show up. So to make sure I wasn't making any mistake I copy pasted the quickstart example and imported a simple mesh made from a cube and it still didn't show up.
But when I downloaded the demo gltf and related files it worked, can you provide any help ?

**Comment by mgsx-dev** [comment]
please make sure you have the right export options, see https://github.com/mgsx-dev/gdx-gltf/blob/master/docs/DOC.md#export-from-blender-280

It would be easier to help you out on Discord if you don't mind: https://libgdx.com/community/discord/
you can ping me in the 3D channel.
