### ISSUE TITLE
GLSL error in cubemap-make.fs.glsl : atan2() should be atan()

### ISSUE THREAD

**Issue by tommyettinger** [mgsx-dev/gdx-gltf#42]
I don't know why GLSL does this, but it doesn't define atan2() in GLSL ES (see [Shaderific for reference](https://www.shaderific.com/glsl-functions)), and instead just uses atan(). This causes IBL Composer to fail on some machines, it seems; Discord user Jaaf showed [this shader compilation error](https://cdn.discordapp.com/attachments/624760161759789057/827974048695975967/unknown.png) which seems directly related to atan2().

You can also just look at the syntax highlighting for `asin()` vs. `atan2()` in https://github.com/mgsx-dev/gdx-gltf/blob/master/ibl-composer/src/net/mgsx/gltf/shaders/cubemap-make.fs.glsl#L26 ; atan2 isn't highlighted but asin is. Some vendors may define atan2() in addition to atan() with two arguments, but I don't think it's ever standard.

**Comment by mgsx-dev** [comment]
It was actually logged as a warning, double self face palm... thank you @tommyettinger
