### ISSUE TITLE
Incomplete rendered object with rigged model

### ISSUE THREAD

**Issue by Dgzt** [mgsx-dev/gdx-gltf#43]
Hi,

I've tried more rigged models, but the model rendering is not complete. Tried with 1.0.0 and master branch, but the results are same.

Here is the rendered object: https://imgur.com/a/UGdtqcU
Here is the code: https://pastebin.com/MXf7Kr7r
And here is the used model: https://www.cgtrader.com/free-3d-models/character/sci-fi/low-poly-military-robot

Best regards,
Dgzt

**Comment by mgsx-dev** [comment]
yes, it's a common pitfall, you probably have more bones in your model than what is configured in shader providers. You need to set more bones in your shader providers configuration. eg. `new SceneManager(32)`.
I'll add something in the documentation about this.

**Comment by dzikoysk** [comment]
Throwing some kind of validation exception could be an option 🤔

**Comment by Dgzt** [comment]
Thank you, as you said this solved the problem:

`final DefaultShader.Config config = new DefaultShader.Config();
config.numBones = 32;
sceneManager = new SceneManager(new DefaultShaderProvider(config), new DepthShaderProvider());`

**Comment by mgsx-dev** [comment]
@Dgzt i added this in troubleshooting section : https://github.com/mgsx-dev/gdx-gltf#rigged-model-partially-rendered

**Comment by Dgzt** [comment]
@mgsx-dev Thank you!

**Comment by mgsx-dev** [comment]
@dzikoysk this is handled at libGDX core level, i'll see if we can perform some kind of validation for those (numBones, lights, etc)

**Comment by mgsx-dev** [comment]
for reference: https://github.com/libgdx/libgdx/pull/6496
