### ISSUE TITLE
Faster BinaryDataFileResolver

### ISSUE THREAD

**Issue by MovementSpeed** [mgsx-dev/gdx-gltf#44]
https://github.com/mgsx-dev/gdx-gltf/blob/01f92b26f4acb77e7edcfdaf68e70d286b05754a/gltf/src/net/mgsx/gltf/loaders/glb/BinaryDataFileResolver.java#L71

Hello, I think I've made an improvement to the creation of the ByteBuffer by using libgdx's StreamUtils:

```java
byte[] arr = StreamUtils.copyStreamToByteArray(stream);
ByteBuffer bufferData = ByteBuffer.allocate(chunkLen);
bufferData.order(ByteOrder.LITTLE_ENDIAN);
bufferData.put(arr);
bufferData.flip();
bufferMap.put(bufferMap.size, bufferData);
```

Old version: 47 seconds
New version: 43 milliseconds

Great job with gdx-gltf by the way!

**Comment by mgsx-dev** [comment]
Thank you very much, it improves loading time drastically, i get 11ms instead of 142ms in my benchmark (13x gain), not as much as yours but i guess it really depends on the content of the file and i'm not surprised you get a 65x gain.
