### ISSUE TITLE
Why texture incomplete when camera move faraway ?

### ISSUE THREAD

**Issue by Just-D** [mgsx-dev/gdx-gltf#47]
I download the model from sketchfab，the model's texture incomplete when camera move faraway, but it's ok when camera close to the model. I'm not writing any code, just using the release jar.

**Comment by mgsx-dev** [comment]
which model? which jar release? which texture?

**Comment by Just-D** [comment]
I used the jar both "gdx-gltf-demo-desktop-2.0.0-preview.jar" and "gdx-gltf-demo-desktop-1.0.0-patch1.jar".
The model have tested is : 
1. https://sketchfab.com/3d-models/forest-warrior-527429928e0349168aa7c29e14a8c1c8   ,  the texture for hair and cloth goes wrong.
2. https://sketchfab.com/3d-models/motelsign-post-apo-170f5144a7544fabbf203199a72e3cc8   , the texture for wood goes wrong.

Camera moving faraway will lead to the problem, if you check it very closely, it' ok.

I'm using AMD's display card now, the screen monitor could blink sometimes . I will test it on Intel's  integrated graphics card and report again.

**Comment by Just-D** [comment]
I‘ve imported the models to Blender, also bad when camera faraway in this computer(Windows, AMD WX4100 graphics card).
But !!! The models work well in another computer(Linux, Intel integrate graphics card) with Blender .
I don't know what happed, and i think your code and jar may working well, perhaps my computer's ENV not good...

**Comment by mgsx-dev** [comment]
yeah, it sounds like an issue with your driver, maybe try to upgrade them on your machine.

I'm closing now since it's not an issue with the library.
