### ISSUE TITLE
What should i do when I use OrthographicCamera to show 3D gltf model ?

### ISSUE THREAD

**Issue by peerless2012** [mgsx-dev/gdx-gltf#48]

**Comment by mgsx-dev** [comment]
please use libgdx discord to get help : https://libgdx.com/community/

short answer: nothing, you simply have to use an OrthographicCamera instead of PerspectiveCamera

**Comment by peerless2012** [comment]
When i change the camera in GLTFDemo from PerspectiveCamera to OrthographicCamera, the model is so small, and how can i do to zoom it to fit the window ?

![image](https://user-images.githubusercontent.com/3116469/120162167-b2da5480-c22a-11eb-8a78-47ca2f123c77.png)

**Comment by peerless2012** [comment]
I use OrthographicCamera zoom to solve , and the zoom is a very small value.
