### ISSUE TITLE
Doubt about rotation

### ISSUE THREAD

**Issue by RoberMS** [mgsx-dev/gdx-gltf#5]
Good afternoon, I have a question about how to rotate, to see if you are so kind to help me.
When I load the gltf file it is shown from a lateral perspective and I would like to rotate it so that it is shown frontally.
thank you very much, I look forward to your help

![Sin-título-1](https://user-images.githubusercontent.com/53574645/68881729-f71c0780-070d-11ea-8ded-d7fe727c4e46.png)

**Comment by mgsx-dev** [comment]
@RoberMS Hi, i don't think your question is related to gdx-gltf but libgdx 3D rotation in general. If you agree, you can close the issue :-).

Anyway, i'll try to help you out : 

You can either rotate your model (90° on Y Axis depending on your axis) in your code or export your model with your desired orientation.

In Blender, to have your desired orientation, you need to put your character facing your front view and make sure  your model have a default rotation (you can apply rotation if it's not the case). For skinned models, it requires more work, you have to deal with your armature as well.

If you need more help about it, you can found me and other cool people on [libgdx discord server](https://libgdx.badlogicgames.com/community.html).

**Comment by RoberMS** [comment]
Thank you for your prompt response, as you can imagine I am starting with libgdx and I am a beginner.
the idea is to do what you mention "rotate the model 90° on Y Axis" but I don't know where to do it from. cameraControl? sceneManager?, I have tried from different places but I have not had luck.
Thanks

**Comment by mgsx-dev** [comment]
3D stuff is not the easiest way to start with libgdx :-) .

Anyway, maybe the best place to rotate your model in your case is on your scene ModelInstance : `scene.modelInstance.transform.rotate(Vector3.Y, 90);`

**Comment by RoberMS** [comment]
It works perfect! Thank you very much for your help.
and congratulations on this fantastic library, it has helped me a lot.
Regards!
