### ISSUE TITLE
Documentation or Example on Rendering Procedural Mesh

### ISSUE THREAD

**Issue by sesteel** [mgsx-dev/gdx-gltf#51]
I've struggled with getting a procedural model to render correctly.  I am building a simple heightmap which displays correctly in the default pipeline; however, after modifying the materials when adding it to a scene it renders black.

![image](https://user-images.githubusercontent.com/1007480/126746182-f92aecb9-6184-44e1-b36a-fec82998c686.png)

I have several models in the same scene rendering on the same SceneManager render call with the same lights.  Is there a particular texture that must be present for lighting to work correctly?  I just want to make sure I am not spinning my wheels in the wrong area.

**Comment by mgsx-dev** [comment]
@sesteel Sorry for the delay. No special texture is necessary to have lighting working correctly. The minimal setup (if i remember correctly) is to have a BaseColor (see PBRColorAttribute.createBaseColorFactor) for your material and normals for your mesh.

**Comment by yuripourre** [comment]
@sesteel I am experiencing the same problem. I am trying to add a cube (built procedurally) and no matter what I try it's always black.

@mgsx-dev let's say the cube has a material with ColorAttribute, does PBRColorAttribute also needs to be defined? Or it should replace the ColorAttribute?

**Comment by mgsx-dev** [comment]
@yuripourre as said in my previous comment, material **should** have a baseColorFactor (PBRColorAttribute.createBaseColorFactor). ColorAttribute.diffuse is not compatible with PBR shader.

**Comment by yuripourre** [comment]
@mgsx-dev thank you, I will do some testing later today.

**Comment by mgsx-dev** [comment]
@yuripourre @sesteel i added a minimal runnable example of procedural model and material [here](https://github.com/mgsx-dev/gdx-gltf/blob/master/gltf/test/net/mgsx/gltf/procedural/ProceduralExample.java)

**Comment by yuripourre** [comment]
@mgsx-dev `PBRColorAttribute.createBaseColorFactor` did the trick, I was trying to use create diffuse instead.

Thank you so much for this example, it is very helpful!
