### ISSUE TITLE
What would be the best way to handle huge meshes?

### ISSUE THREAD

**Issue by yuripourre** [mgsx-dev/gdx-gltf#53]
@mgsx-dev I know that the limitations of the number of vertices/indexes comes from libGDX. I also know that is always possible to break the mesh using a 3D software.
But let's say for the sake of convenience it needs to be handled via code. What do you think would be the best approach?

The way I can think of is (when loading a mesh): to load a mesh into an intermediate structure that would handle indexes as `integers` and the whole mesh as a list of edges. Then create multiple planes(or boxes) to slice the mesh (for each sliced edge, it would become two smaller edges). 
And after slicing "enough" each chunk (defined by planes) would become a new mesh node (with less indexes than the original mesh).

Do you think that approach would work? Can you think of a simpler way to do it?

**Comment by mgsx-dev** [comment]
i already did it few weeks ago :-) https://github.com/mgsx-dev/gdx-gltf/commit/5a65f3ea83bf9dcb7074e236bdefbc11d45d0a02

There are no longer limitations.

**Comment by yuripourre** [comment]
Whoa, seems that I missed that. Thank you once again!
