### ISSUE TITLE
Frustum culling renderables

### ISSUE THREAD

**Issue by krojew** [mgsx-dev/gdx-gltf#54]
SceneManager currently seems to render everything - it would be great if it checked which objects are in the frustum (for shadows too).

**Comment by mgsx-dev** [comment]
hi, sorry for the delay.. the thing is some models may have animations, some other could be dynamic, so it's not possible to have that information. It's user code responsibility to perform culling depending on their scenes.

**Comment by mgsx-dev** [comment]
@krojew actually you can by using sceneManager.getRenderableProviders and manage this list yourself, or by implementing your own RenderableProvider (with culling).
SceneManager is well suited for basic stuff, and for beginners, so if you have more complex handling and features, i suggest you to implement your own.
