### ISSUE TITLE
Load pixmap from bytes in WebGL

### ISSUE THREAD

**Issue by yuripourre** [mgsx-dev/gdx-gltf#55]
Hello @mgsx-dev, I am trying to run a project using gdx-gltf in the browser using gwt but I am getting this error on the console:

```
GwtApplication: exception: load pixmap from bytes not supported for WebGL
```
The exception is thrown by [PixmapBinaryLoaderHack.java](https://github.com/mgsx-dev/gdx-gltf/blob/master/gltf/src/net/mgsx/gltf/loaders/shared/texture/PixmapBinaryLoaderHack.java)

Edit: Originally I thought the limitation was on gdx-gltf but I found that the GWT Pixmap has no construtor using array of bytes. This is a limitation of libGDX I am doing some research.

**Comment by yuripourre** [comment]
Ok, I just found it in the Readme.md: https://github.com/mgsx-dev/gdx-gltf#webgl-limitations

**Comment by mgsx-dev** [comment]
considering you closed your libgdx PR https://github.com/libgdx/libgdx/pull/6738 i think we'll keep it as a limitation for now
