### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by SergeyPentsov** [mgsx-dev/gdx-gltf#70]
Hello everybody!
I tried to use this lib to load gltf files and see the following issues.
First of all, I've used code from JamesTKhan youtube channel and seen a lot of artifacts after model loading. It's reproduced with a cube, monkey, and model from a youtube channel.
Also, I've downloaded the demo and loaded it to demo all these models, and it seems good before I want to scale them. If I scale the model to a small size, it's also reproduced.
I have windows 10, JDK 11. 
Do you know what a problem is and how I can fix that?
Regards!

**Comment by JamesTKhan** [comment]
Could you provide a screenshot of the artifacts you are seeing and the model file?

**Comment by SergeyPentsov** [comment]
Hi!
First of all, I used the model from https://github.com/JamesTKhan/gdx-gltf-starter/tree/main/core/assets/models with the load codebase from this lesson and, but with the modern engine version(I've checked your project, it's not depend on the version and also check in original project).
![image](https://user-images.githubusercontent.com/3229388/180594538-2cc54a39-9127-4422-8d46-9b0ef4f99ae3.png)
![image](https://user-images.githubusercontent.com/3229388/180594567-0d7294d9-f0fc-44b0-902b-5f3ac3feec46.png)
![image](https://user-images.githubusercontent.com/3229388/180594578-64079747-0e59-4f09-b6c9-84dfd7d161de.png)
If you need more examples, let me know.

**Comment by JamesTKhan** [comment]
Thanks for the screenshots. I was doing some testing on the same code base with the alien slime. The only way I could _kind of_ replicate that artifacting is by changing the depth functions (which I assume you are not doing ?) 

I am not sure this is a issue with the gdx-gltf library specifically. I recommend to bring this issue up in the LibGDX 3d discord instead (good place to get support on issues like these).

**Comment by SergeyPentsov** [comment]
No, I've used only the codebase from the youtube channel and don't change anything like depth functions.
Thx, I mb will be talking about that in discord.

**Comment by SergeyPentsov** [comment]
Also, I've continued to test in the original demo jar and provided you new screenshots:
![image](https://user-images.githubusercontent.com/3229388/180620212-80b2507a-9ddb-4290-b388-6f34a043f2fc.png)
![image](https://user-images.githubusercontent.com/3229388/180620227-222b13a1-6199-4128-8256-cc3509f3c259.png)

**Comment by mgsx-dev** [comment]
as discussed in Discord, your issue was related to intel integrated graphics card, and work perfectly with your dedicated GPU. It seems that depth buffer has a very low resolution (8 bit or something) where normally should support at least 16 bit depth buffer.  It's a known but very rare bug that we can't fix in libgdx or gdx-gltf so i'm clisong the issue.

The know and working workaround is to render to a frame buffer, so you could do that if needed.
