### ISSUE TITLE
Adding new GLTF extensions

### ISSUE THREAD

**Issue by MikOfClassX** [mgsx-dev/gdx-gltf#75]
Hi,

is there any starting point in order to add some missing extensions to gdx-gltf ?

i.e.
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_transmission
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_volume

Cheers!

**Comment by mgsx-dev** [comment]
not in my schedule yet, but if someone want to contribute, it would be very appreciated. Some pointers : 
https://github.com/KhronosGroup/glTF-Sample-Viewer have implemented them so it could be a good base for the shader part (which is the hardest part).

Do you plan to add them?

**Comment by MikOfClassX** [comment]
I'm getting started with libGDX and gdx-GLTF. I'm already getting very good results and I'm going to push some small mods, fixes, i.e. thread-safety issues when using both libs in multithreaded shared GL contexts.

The next step may be the implementation of some extra features. Those extensions are quite interesting. I have to dig more into gdx-GLTF in order to see how to integrate the shaders.

**Comment by minyor** [comment]
Implemented native support for KHR_mesh_quantization to fix this. You can find the implementation in my fork:
https://github.com/minyor/gdx-gltf-KHR

Yes, it is without shaders support but at least for my use case it is working and for me it is better than nothing.
