### ISSUE TITLE
Capturing scene displays only the skybox via FBO

### ISSUE THREAD

**Issue by ronjunevaldoz** [mgsx-dev/gdx-gltf#76]
How to properly capture the whole scene FBO using scene manager? 

### Example fbo capturing
```kotlin
// capture reflection
sceneManager.renderShadows()
reflectionFbo.begin()
Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT or GL20.GL_DEPTH_BUFFER_BIT)
sceneManager.renderColors()
reflectionFbo.end()
```
### Actual screenshot of fbo
![image](https://user-images.githubusercontent.com/4947998/187694806-fac05a34-05ea-4145-abe1-8eb03819ba8f.png)

**Comment by mgsx-dev** [comment]
Hi, it looks like your framebuffer doesn't have depth buffer, maybe you forgot to set it during its creation.

For questions and help, please use discord server instead : https://libgdx.com/community/
