### ISSUE TITLE
Finding the intersection of scenes

### ISSUE THREAD

**Issue by RazuvaevDD** [mgsx-dev/gdx-gltf#85]
Hi, is there a good way to find intersections between scenes? 
What is the right/best way to do this from your point of view?
Thank you in advance, if this is displayed in the documentation, it will greatly help beginners and not only correctly implement collisions and other functionality:)

**Comment by mgsx-dev** [comment]
Hi, physics and collision detection are not part of the library, you should better ask to the libgdx discord : https://libgdx.com/community/
